# Hack fix to force ansible to evaluate the variable, as it may not be in scope in easy-includes
- local_action: command echo {{ easy_send_metadata_to_datacite_version }}
  become: no
  register: mod_version

- include_role:
    name: dans.easy-includes
    tasks_from: install_easy_module
  vars:
    easy_module_name: "easy-send-metadata-to-datacite"
    easy_module_version: "{{ mod_version.stdout }}"

- include_role:
    name: dans.easy-includes
    tasks_from: install_cmd
  vars:
    easy_module_name: "easy-send-metadata-to-datacite"
    easy_module_version: "{{ mod_version.stdout }}"

- name: Configure application
  replace: dest={{ easy_modules_installation_base_path }}/easy-send-metadata-to-datacite/cfg/application.properties
           regexp="^{{ item.key }}.*$"
           replace="{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'send.metadata.to.datacite.report.file', value: '{{ easy_send_metadata_to_datacite_report_file }}' }
    - { key: 'datacite.registration.doi.uri', value: '{{ easy_send_metadata_to_datacite_registration_doi_uri }}' }
    - { key: 'datacite.registration.metadata.uri', value: '{{ easy_send_metadata_to_datacite_registration_metadata_uri }}' }
    - { key: 'datacite.username', value: '{{ easy_send_metadata_to_datacite_username }}' }
    - { key: 'datacite.password', value: '{{ easy_send_metadata_to_datacite_password }}' }
    - { key: 'datacite.resolver', value: '{{ easy_send_metadata_to_datacite_resolver }}' }
    - { key: 'solr.query.base', value: '{{ easy_send_metadata_to_datacite_solr_query_base }}' }
    - { key: 'fcrepo.url', value: '{{ easy_send_metadata_to_datacite_fcrepo_url }}' }
    - { key: 'fcrepo.user', value: '{{ easy_send_metadata_to_datacite_fcrepo_user }}' }
    - { key: 'fcrepo.password', value: '{{ easy_send_metadata_to_datacite_fcrepo_password }}' }
