- include: install.yml
  when: (ansible_local is undefined)
        or (ansible_local.easy_send_metadata_to_datacite is undefined)
        or ((force_reinstalls is defined) and (force_reinstalls|bool))